# Jekyll configuration / customisation
title: &project_title Wall Moisture Sensor - WSM1
description: &project_description >- 
  Monitor wall moisture using capacitive sensors.
  The device supports two methods for reading capacitive values, allowing for comparison and experimentation.

project: 
  name: wall_moisture-hardware
  title: *project_title
  description: *project_description
  company: "EL-ED"
  repository: https://github.com/miqap/wall-moisture-sensor

    

  manufacturers: ["jlcpcb"]
