title: WallMoisture
description: >- 
  Some Description to write
baseurl: ""
url: ""
permalink: /:slug
theme: just-the-docs
plugins:
  - jemoji

highlighter: rouge

sass:
  style: :compressed


# Just the Docs theme options
just_the_docs:
  logo: "/assets/images/logo.png"       # Optional: path to your logo
  search_enabled: true                  # Enable search
  heading_anchors: true                 # Add anchor links to headings
  aux_links:
    GitHub Repository: https://github.com/miqap/wall-moisture


# Below file names are hardcode and are dependent to the github action configuration
project: 
  renders:
    - title: "Render Top Angled"
      image_suffix: "-3d_top_angled.png"
    - title: "Render Top"
      image_suffix: "-3d_top.png"
    - title: "Render Bottom"
      image_suffix: "-3d_bottom.png"

  schematic_variants:
    - name: "Dark"
      file_suffix: "-schematic-dark.pdf"
    - name: "Monochromatic"
      file_suffix: "-schematic-mono.pdf"
    - name: "Light"
      file_suffix: "-schematic-default.pdf"

  assembly_variants:
    - name: "Dark"
      file_suffix: "-pcb-dark.pdf"
    - name: "Light"
      file_suffix: "-pcb-light.pdf"

  manufacturers: ["JLCPCB", "Eurocircuits"]

