# Action triggered on release branche
name: Release Actions

on:
  pull_request:
    branches:
      - release
      - test-ci-workflow
env:
  # we’ll use `yq` to read project.yml
  PROJECT_CONFIGURATION: project.yml


permissions:
  contents: read
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      project_name: ${{ steps.load.outputs.project_name }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Load project.yml into outputs
        id: load
        run: |
          echo "project_name=$(yq e '.project.name' ${{ env.PROJECT_CONFIGURATION }})" >> $GITHUB_OUTPUT


  preflight:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad9_auto_full:latest
    needs: setup
    env:
      PROJECT_NAME: ${{ needs.setup.outputs.project_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: "1"
          submodules: "true"

      - name: Run Kibot ERC/DRC
        uses: INTI-CMNB/KiBot@v2_k9
        id: erc_drc
        with:
          config: ci/preflight_enforce.kibot.yaml
          dir: output
          schema: "${{ env.PROJECT_NAME }}.kicad_sch"
          board: "${{ env.PROJECT_NAME }}.kicad_pcb"
          verbose: 1
