# Action triggered on release branche
name: Release Actions

on:
  pull_request:
    branches:
      - release
      - test-ci-workflow
env:
  # we’ll use `yq` to read project.yml
  PROJECT_CONFIGURATION: project.yml


permissions:
  contents: read
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      project_name: ${{ steps.load.outputs.project_name }}
      prefix:       ${{ steps.load.outputs.prefix }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Load project.yml into outputs
        id: load
        run: |
          echo "project_name=$(yq e '.project.name' ${{ env.PROJECT_CONFIGURATION }})" >> $GITHUB_OUTPUT
          echo "prefix=$(yq e '.project.schematic_prefix' ${{ env.PROJECT_CONFIGURATION }})" >> $GITHUB_OUTPUT


  preflight:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad9_auto_full:latest
    needs: setup
    env:
      PROJECT_NAME: ${{ needs.setup.outputs.project_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: "1"
          submodules: "true"

      - name: Run Kibot ERC (schematic)
        uses: INTI-CMNB/KiBot@v2_k9
        id: erc
        continue-on-error: true
        with:
          config: ci/preflight_enforce.kibot.yaml
          dir: output
          skip: run_drc
          schema: "${{ env.PROJECT_NAME }}.kicad_sch"
          board: "${{ env.PROJECT_NAME }}.kicad_pcb"
          verbose: 1

      - name: Run Kibot DRC (layout)
        uses: INTI-CMNB/KiBot@v2_k9
        id: drc
        continue-on-error: true
        with:
          config: ci/preflight_enforce.kibot.yaml
          dir: output
          skip: run_erc
          schema: "${{ env.PROJECT_NAME }}.kicad_sch"
          board: "${{ env.PROJECT_NAME }}.kicad_pcb"
          verbose: 1

      - name: "Setup jq"
        uses: dcarbone/install-jq-action@v2
      - name: Parse ERC
        run: |
          erc_warnings=$(cat output/$PROJECT_NAME-erc.json | jq '[try .violations[] | select(.severity == "warning")] | length')
          erc_errors=$(cat output/$PROJECT_NAME-erc.json | jq '[try .violations[] | select(.severity == "error")] | length')
          cat <<EOF > output/erc_validation.md
          ### ERC Report
          - **Errors**: $erc_errors
          - **Warnings**: $erc_warnings
          - **Link**: [HTML Report]($PROJECT_NAME-erc.html)
          EOF
          cat output/erc_validation.md
      - name: Parse DRC
        run: |
          drc_warnings=$(cat output/$PROJECT_NAME-drc.json | jq '[try .violations[] | select(.severity == "warning")] | length')
          drc_errors=$(cat output/$PROJECT_NAME-drc.json | jq '[try .violations[] | select(.severity == "error")] | length')
          cat <<EOF > output/drc_validation.md
          ### DRC Report
          - **Errors**: $drc_errors
          - **Warnings**: $drc_warnings
          - **Link**: [HTML Report]($PROJECT_NAME-drc.html)
          EOF
          cat output/drc_validation.md

      - name: Fail if any Kibot step failed
        if: |
          steps.erc.outcome == 'failure' ||
          steps.drc.outcome == 'failure'
        run: |
          if [ "${{ steps.erc.outcome }}" = "failure" ]; then
            echo "❌ ERC Step : Failed"
          fi
          if [ "${{ steps.drc.outcome }}" = "failure" ]; then
            echo "❌ DRC Step : Failed"
          fi
          exit 1
